"""Type stubs for pytroska._pytroska_core Rust extension module."""

def core_version() -> str: ...

class PytroskaError(Exception): ...
class ParseError(PytroskaError): ...
class CorruptedError(PytroskaError): ...
class UnsupportedError(PytroskaError): ...
